### ISSUE TITLE
请问大佬，lfw_pair.txt文件怎么看呀？

### ISSUE THREAD

**Issue by HeBangYan** [bubbliiiing/arcface-pytorch#11]
非常感谢大佬无私地分享！:)

请问一下，[lfw_pair.txt](https://github.com/bubbliiiing/arcface-pytorch/blob/989359e85fe61d37ba01f61a1ae2720b550e0194/model_data/lfw_pair.txt#L1)里的数字都表示什么含义呀？

**Comment by bubbliiiing** [comment]
https://blog.csdn.net/zhongzhongzhen/article/details/78293789

**Comment by HeBangYan** [comment]
谢谢大佬
