### ISSUE TITLE
 关于image_shape的问题

### ISSUE THREAD

**Issue by Yurzi** [bubbliiiing/arcface-pytorch#28]
请问在该实现中训练的时候image_shape必须是112x112x3的吗，是否可以使用不同长宽和长宽比的图片？

**Comment by bubbliiiing** [comment]
0 0额会resize，没事

**Comment by Yurzi** [comment]
owo?
dataloader中确实存在`resize_image`', 但是这个resize似乎并不是 resize到固定大小？（可能咱太蠢了）
但是在`iresnet.py`的`self.fc` 这个全连接层处，其接受的向量又是固定的。

咱也在自己实现一个arcface, 所以想请教下怎么做到的

**Comment by bubbliiiing** [comment]
是固定大小的
112x112

**Comment by audengxiao** [comment]
> 是固定大小的 112x112

不需要对输入图像作人脸检测和人脸对齐吗
