### ISSUE TITLE
test result is lower

### ISSUE THREAD

**Issue by jack-gits** [bubbliiiing/arcface-pytorch#3]
我用你提供的lfw数据和模型，得到如下结果。 与期望的accuracy 99.1，有些差距。

Accuracy: 0.98800+-0.00722
Best_thresholds: 1.17000
Validation rate: 0.92400+-0.02086 @ FAR=0.00100

**Comment by jack-gits** [comment]
我的错误

**Comment by bubbliiiing** [comment]
好的0 0
