### ISSUE TITLE
arcface_mobilefacenet.pth文件较大

### ISSUE THREAD

**Issue by David1007587693** [bubbliiiing/arcface-pytorch#5]
你好，看到你提供的预训练模型在4M左右，为什么我训练出来的在9M左右呢？会是什么原因呢？
![image](https://user-images.githubusercontent.com/24688805/160827426-15427441-6c19-479e-8154-db215e28661b.png)

**Comment by David1007587693** [comment]
这个地方我不是很懂，是完成训练后再对权重文件.pth进行处理吗？

**Comment by David1007587693** [comment]
学了一下是这样
import torch
content = torch.load('test.pth')
content.pop('head.weight')
torch.save(content, './test_2.pth')
感谢大哥！

**Comment by bubbliiiing** [comment]
确实可以

**Comment by juren1** [comment]
> 你好，看到你提供的预训练模型在4M左右，为什么我训练出来的在9M左右呢？会是什么原因呢？ ![image](https://user-images.githubusercontent.com/24688805/160827426-15427441-6c19-479e-8154-db215e28661b.png)

大佬，我也复现训练了这个模型，但是我只训练了100轮，训练100轮最后显示的训练集验证集正确率却只有0.5左右，但是我拿LFW进行评估却已经达到0.99左右，这正常吗？还是说我现在要把训练轮数加长？有什么建议吗？大佬 @David1007587693 @bubbliiiing
